### ISSUE TITLE
"Share this" still broken

### ISSUE THREAD

**Issue by retsifp** [smarek/Simple-Dilbert#40]
I can't reopen #35, so I opened a new issue.

Unfortunately, "Share this" is still broken for me with v4.4 🙁 

When I try to share with WhatsApp, I get the message "Sharing failed, please try again", but it doesn't work, no matter how often I try it. 😉 

When sharing with Signal or K9Mail, only the text and the link to the image is shared, not the image as it was the case with v4.2

Phone: Fairphone FP2 with Android 5.1

**Comment by smarek** [comment]
Sorry to hear that, could you probably look into logcat and provide error that's shown in it? I don't know, where the issue may happen. If not, I could probably provide version of app, that allows user to create and send bug-report in case of caught exception.

**Comment by retsifp** [comment]
I'm not sure this is everything, I have **a lot** more in the logcat even when on flight mode  :sweat_smile:
```
I/Timeline(  995): Timeline: Activity_windows_visible id: ActivityRecord{12861f35 u0 com.mareksebera.simpledilbert/.core.DilbertFragmentActivity t1307} time:94502077
I/WindowManager(  995): Screen frozen for +598ms due to Window{13dccb38 u0 com.mareksebera.simpledilbert/com.mareksebera.simpledilbert.core.DilbertFragmentActivity}
W/WindowManager(  995): Failed looking up window
W/WindowManager(  995): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@14701e26 does not exist
W/WindowManager(  995): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8578)
W/WindowManager(  995): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8569)
W/WindowManager(  995): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2594)
W/WindowManager(  995): 	at com.android.server.wm.Session.remove(Session.java:187)
W/WindowManager(  995): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3015)
W/WindowManager(  995): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5502)
W/WindowManager(  995): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3321)
W/WindowManager(  995): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager(  995): 	at android.os.Looper.loop(Looper.java:135)
W/WindowManager(  995): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/WindowManager(  995): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by smarek** [comment]
This is not an SimpleDilbert isssue, is there anything in LogCat, that starts with `E/DilbertFragment` or `W/DilbertFragment` ? Also may be something similar

**Comment by smarek** [comment]
Closing for inactivity
