### ISSUE TITLE
"Export cached URLs" functionality crashes

### ISSUE THREAD

**Issue by mnalis** [smarek/Simple-Dilbert#64]
Trying to click `EXPORT CACHED URLS` on `EMUI 12.0.0` phone with f-droid SimpleDilbert `4.7` crashes the app with:

```
03-24 19:08:39.850  8835  8835 V AudioManager: querySoundEffectsEnabled...
03-24 19:08:39.993  8835  8835 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3189520)
03-24 19:08:39.994  8835  8835 I BlockMonitor: dispatchingThrewException In MainThread
03-24 19:08:39.994  8835  8835 D AndroidRuntime: Shutting down VM
03-24 19:08:39.994  8835  8835 I QarthLog: [PatchStore] createDisableExceptionQarthFile
03-24 19:08:39.994  8835  8835 I QarthLog: [PatchStore] create disable file for com.mareksebera.simpledilbert uid is 10204
--------- beginning of crash
03-24 19:08:39.994  8835  8835 E AndroidRuntime: FATAL EXCEPTION: main
03-24 19:08:39.994  8835  8835 E AndroidRuntime: Process: com.mareksebera.simpledilbert, PID: 8835
03-24 19:08:39.994  8835  8835 E AndroidRuntime: java.lang.RuntimeException: Failure from system
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1748)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5412)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at androidx.e.a.d.startActivityForResult(Unknown Source:10)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5337)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at androidx.e.a.d.startActivityForResult(Unknown Source:10)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5819)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5787)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at com.mareksebera.simpledilbert.preferences.DilbertPreferencesActivity$3.onClick(Unknown Source:109)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.view.View.performClick(View.java:7317)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7291)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.view.View.access$3600(View.java:838)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28247)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
03-24 19:08:39.994  8835  8835 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 3189520 bytes
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:535)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3904)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1738)
03-24 19:08:39.994  8835  8835 E AndroidRuntime:        ... 18 more
03-24 19:08:40.007  8835  8835 I Process : Sending signal. PID: 8835 SIG: 9

``` 

As a user of many years, I was hoping it might work to help me extract strips I've marked as favourites (especially I can no longer browse most of them in the app due to https://github.com/smarek/Simple-Dilbert/issues/63#issuecomment-1481419667)

**Comment by smarek** [comment]
I can provide separate action, that will export into file, since the text content is too large to share. Something like "dilbert-urls-{timestamp of export}.txt" in external storage. What do you think?

**Comment by mnalis** [comment]
Export to file looks good to me as a workaround - whatever works!

_(I have no experience until now with too large share content. In fact, I was able to use share functionality (e.g. via ShareviaHTTP or similar) of hundred of MB without problems, so I wasn't even aware there was an Android share size limit)_
